name: cron workflow

on:
  schedule:
    - cron: "*/5 * * * *"
    - cron: "*/20 1 * * *"
  workflow_dispatch:

jobs:
  cron_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "cron workflow"

