name: first workflow
on:
  push:
    branches:
      - "main" 
jobs:
  first_workflow:  
    name: first job
    runs-on: ubuntu-latest 
    steps:
      - name: efore checkout action
        run: ls
        shell: bash

      - name: checkout steps
        uses: actions/checkout@v5

      - name: after checkout action
        run: ls
        shell: bash